 ---
on: push
name: Build and publish
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build
        run: env FRAMER_TOKEN=${{ secrets.FRAMER_TOKEN }} npx framer-cli build Funda.framerfx

      - name: Publish
        uses: framer/bridge@master
        env:
          FRAMER_TOKEN: ${{ secrets.FRAMER_TOKEN }}
        with:
          args: publish Funda.framerfx --yes