---
on: push
name: Build and publish funda design system
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build
        uses: framer/bridge@master
        with:
          args: build <Funda.framerfx>

      - name: Publish
        uses: framer/bridge@master
        env:
          FRAMER_TOKEN: ${{ secrets.e8731f32-00a1-4f5d-be19-94bd2f2ea87b }}
        with:
          args: publish <Funda.framerfx> --yes
